# Generated by Django 4.1.5 on 2023-04-23 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0013_team_requests_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='hack_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=255)),
                ('userid', models.CharField(max_length=255)),
                ('hackathon_name', models.CharField(max_length=255)),
            ],
        ),
    ]
