# Generated by Django 4.1.5 on 2023-04-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0014_hack_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammatesearch',
            name='developer_role_required',
            field=models.CharField(default='developer', max_length=255),
        ),
        migrations.AddField(
            model_name='teammatesearch',
            name='preffered_languages',
            field=models.CharField(default='python', max_length=255),
        ),
    ]
