# Generated by Django 4.1.5 on 2023-04-22 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_activation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='activation',
            name='github_username',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
