# Generated by Django 4.1.5 on 2023-04-22 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_activation_github_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activation',
            name='github_username',
        ),
    ]
