# Generated by Django 4.1.5 on 2023-04-23 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='savematches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='match name', max_length=100)),
                ('userid_sender', models.BinaryField()),
                ('userid_rec', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='swipeprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Looking_for', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('analyse_profile', models.CharField(max_length=100)),
            ],
        ),
    ]
